version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_APP_API_URL=http://app/api/v1/test

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
    restart: unless-stopped
    depends_on:
      - web

  app:
    build: .
    environment:
      - VITE_APP_API_URL=http://app/api/v1/test
    # ... diğer konfigürasyonlar

networks:
  default:
    name: cloudflare_network