version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_APP_API_URL=http://app/api/v1/test
    networks:
      - external-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`pixelpickle.net`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
    restart: unless-stopped
    depends_on:
      - frontend
    networks:
      - external-net

networks:
  external-net:
    external: true