version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
    restart: unless-stopped
    depends_on:
      - web

networks:
  default:
    name: cloudflare_network